export enum StatusCode {
    UNAUTHORIZED = 401,
    NOT_FOUND = 404
}

export enum RequestMethod {
    GET = "GET",
    HEAD = "HEAD",
    POST = "POST",
    PUT = "PUT",
    DELETE = "DELETE",
    CONNECT = "CONNECT",
    OPTIONS = "OPTIONS",
    TRACE = "TRACE",
    PATCH = "PATCH"
}

export enum Language {
    ar = "ar",
    de = "de",
    en = "en",
    es = "es",
    fr = "fr",
    he = "he",
    it = "it",
    nl = "nl",
    no = "no",
    pt = "pt",
    ru = "ru",
    sv = "sv",
    ud = "ud",
    zh = "zh"
}

export enum Category {
    business = "business",
    entertainment = "entertainment",
    general = "general",
    health = "health",
    science = "science",
    sports = "sports",
    technology = "technology"
}

export enum Country {
    ae = "ae",
    ar = "ar",
    at = "at",
    au = "au",
    be = "be",
    bg = "bg",
    br = "br",
    ca = "ca",
    ch = "ch",
    cn = "cn",
    co = "co",
    cu = "cu",
    cz = "cz",
    de = "de",
    eg = "eg",
    fr = "fr",
    gb = "gb",
    gr = "gr",
    hk = "hk",
    hu = "hu",
    id = "id",
    ie = "ie",
    il = "il",
    in = "in",
    it = "it",
    jp = "jp",
    kr = "kr",
    lt = "lt",
    lv = "lv",
    ma = "ma",
    mx = "mx",
    my = "my",
    ng = "ng",
    nl = "nl",
    no = "no",
    nz = "nz",
    ph = "ph",
    pl = "pl",
    pt = "pt",
    ro = "ro",
    rs = "rs",
    ru = "ru",
    sa = "sa",
    se = "se",
    sg = "sg",
    si = "si",
    sk = "sk",
    th = "th",
    tr = "tr",
    tw = "tw",
    ua = "ua",
    us = "us",
    ve = "ve",
    za = "za"
}
