# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node
#
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Develop Tests & CI / CD

on:
    push:
        branches: [ "develop" ]
    pull_request:
        branches: [ "develop" ]

jobs:
    build-test-deploy:

        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
            - name: Set environment, git username and email
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                  git config --global user.name "${{ github.actor }}"
            - name: Create environment file
              run: |
                  touch .env
                  echo "VITE_CTP_PROJECT_KEY=${{ secrets.VITE_CTP_PROJECT_KEY }}" >> .env
                  echo "VITE_CTP_CLIENT_ID=${{ secrets.VITE_CTP_CLIENT_ID }}" >> .env
                  echo "VITE_CTP_CLIENT_SECRET=${{ secrets.VITE_CTP_CLIENT_SECRET }}" >> .env
                  echo "VITE_CTP_REGION=${{ vars.VITE_CTP_REGION }}" >> .env
                  cat .env
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Run unit tests
              run: npm run test:unit
            - name: Deploy
              run: npm run deploy
